### ISSUE TITLE
Renaming of the project following the new community policy

### ISSUE THREAD

**Issue by 0x2b3bfa0** [helpfulengineering/experience-tagger#1]
https://docs.google.com/document/d/1x77ilAEthTjaolLSBE5yr99cwBjjI5ckCgVbUxiXSQ4/edit?usp=sharing

**Comment by 0xken** [comment]
I'm open to rename this to what fits the standard. Would you like it changed to `project-experience-tagger`? 

This really isn't a project though. It's more a utility to manipulate data for multiple projects to help them get started.

**Comment by 0x2b3bfa0** [comment]
Closing because of its lack of relevance
