### ISSUE TITLE
Generating skills.txt

### ISSUE THREAD

**Issue by 0x2b3bfa0** [helpfulengineering/experience-tagger#3]
Is the `skills.txt` file being created though spontaneous generation? After reviewing the code, I'm unable to find the source of the file.

**Comment by 0x2b3bfa0** [comment]
After talking with @psprings and doing a bit of digital archeology, I've found **[aradchoudhari/LinkedIn-Skills-Crawler/output/all_skills.txt](https://github.com/varadchoudhari/LinkedIn-Skills-Crawler/blob/master/output/all_skills.txt)**, and it looks similar to (though much wider than) the [`./sample-data/skills.txt`](/sample-data/skills.txt) file in this repository.

**Comment by gh0stalker** [comment]
@0x2b3bfa0 The file was a static output from a Linkedin Skills dump provided by Kaggle. The one linked above looks like a possible replacement you can use.

**Comment by 0x2b3bfa0** [comment]
@gh0stalker, thank you! Fixed by #4
